services:
  postgres:
    image: postgres:15
    container_name: postgres-quarkus
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: desafio_picpay
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: